---
# file: master.yml
- hosts: master
  become: yes
  roles:
     - role: common
       vars:
          user: faas-edge-master
          nvidia: "yes"
          proxy: "none"
     - role: k3s-master-reset
     - role: docker
     - role: k3s-master