---
# file: master.yml
- hosts: master
  become: yes
  roles:
     - role: k3s-master-after-join
       vars:
          user: faas-edge-master
          nvidia: "no"
          proxy: "none"
     - role: helm
     - role: openfaas
     - role: monitoring
