---
# file: minion.yml
- hosts: minion
  become: yes
  roles:
     - role: common
       vars:
          user: faas-edge-worker
          nvidia: "no"
          proxy: "none"
          os_environment:
            - key: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
     - role: docker
     - role: k3s-minion-reset
     - role: k3s-minion
