---
# file: roles/docker/tasks/main.yml
- name: Uninstall old packages
  apt:
    state: absent
    pkg:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc

- name: Install requirements
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

#- name: Add a GPG key
#  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: Get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture

- name: Add repository for docker
  apt_repository:
    repo: deb [arch={{ deb_architecture.stdout }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present

- name: Install packages
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  # https://github.com/ansible/ansible/issues/51663
  register: result
  until: result is not failed
  retries: 12 # Wait up to 1 min
  delay: 5

- name: Adding existing user '{{ user }}' to group docker
  user:
    name: "{{ user }}"
    groups:
      - docker
    append: yes

- name: Copy docker daemon config to host (nvidia)
  copy:
    src: "{{ role_path }}/files/daemon-nvidia.json"
    dest: /etc/docker/daemon.json
  when: nvidia == "yes"

- name: Copy docker daemon config to host (normal)
  copy:
    src: "{{ role_path }}/files/daemon.json"
    dest: /etc/docker/daemon.json
  when: nvidia == "no"

- name: Creates directory for proxy
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    recurse: yes
  when: proxy == "tum"

- name: Copy proxy-file
  copy:
    src: "{{ role_path }}/files/http-proxy.conf"
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
  when: proxy == "tum"

- name: reload systemd
  command: systemctl daemon-reload

- name: Enable service docker
  systemd:
    name: docker
    enabled: yes
    state: restarted