apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: mock-powermeasurement-server
  labels:
    app: mock-powermeasurement-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-powermeasurement-server
  template:
    metadata:
      labels:
        app: mock-powermeasurement-server
    spec:
      containers:
      - name: mock-powermeasurement-server
        image: phyz1x/mock-powermeasurement-server:1.0.0
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 250m
            memory: 180Mi
          requests:
            cpu: 102m
            memory: 180Mi
        ports:
        - containerPort: 10000