- pause: seconds=120
- name: give edge nodes labels
  become: True
  command: "{{ item }}"
  with_items:
    - kubectl label node ubuntu20-04-virtualbox nodetype=cloud
    - kubectl label node orange-finch nodetype=edge
    - kubectl label node pynq nodetype=edge
    - kubectl label node odroidxu4-cff203c7 nodetype=edge
    - kubectl label node odroidxu4-1865bd93 nodetype=edge
    - kubectl label node raspberrypi nodetype=edge
